#
# Copyright (c) 2020-2023 SECOM CO., LTD. All Rights reserved.
#
# SPDX-License-Identifier: BSD-2-Clause
#

CFLAGS = -Wall -g
LDFLAGS = $(CMD_LD) -lt_cose -lqcbor -lm
INC = $(CMD_INC) -I ./inc -I ./examples/inc
TARGET = ./bin/cose_parser
SRCS = \
	examples/cose_parser_main.c \
	examples/suit_examples_common.c \
	src/suit_common.c \
	src/suit_digest.c \
	src/suit_cose.c \
	src/suit_manifest_decode.c \
	src/suit_manifest_print.c
OBJDIR = ./obj
OBJS = $(addprefix $(OBJDIR)/,$(patsubst %.c,%.o,$(SRCS)))

ifeq ($(MBEDTLS),1)
    # use MbedTLS
    CFLAGS += -DLIBCSUIT_PSA_CRYPTO_C=1
    #LDFLAGS += -lmbedtls -lmbedx509
    LDFLAGS += -lmbedcrypto
else
    # use OpenSSL
    MBEDTLS=0
    LDFLAGS += -lcrypto
endif

.PHONY: all
all: $(TARGET)

./obj/examples/:
	mkdir -p $(dir $@)

./obj/src/:
	mkdir -p $(dir $@)

$(OBJDIR)/%.o: %.c ./obj/examples/ ./obj/src/
	$(CC) $(CFLAGS) $(INC) -o $@ -c $<

$(TARGET): $(OBJS)
	$(CC) -o $@ $^ $(LDFLAGS)

.PHONY: clean
clean:
	$(RM) $(OBJS) $(TARGET)

SOURCES := \
	./testfiles/es_dh_p256_a128gcm_a256kw.cose \
	./testfiles/es_dh_p256_a128gcm_a192kw.cose \
	./testfiles/es_dh_p256_a128gcm_a128kw.cose \
	./testfiles/es_dh_p256_a192gcm_a256kw.cose \
	./testfiles/es_dh_p256_a192gcm_a192kw.cose \
	./testfiles/es_dh_p256_a192gcm_a128kw.cose \
	./testfiles/es_dh_p256_a256gcm_a256kw.cose \
	./testfiles/es_dh_p256_a256gcm_a192kw.cose \
	./testfiles/es_dh_p256_a256gcm_a128kw.cose \
	./testfiles/es_dh_p384_a128gcm_a256kw.cose \
	./testfiles/es_dh_p384_a128gcm_a192kw.cose \
	./testfiles/es_dh_p384_a128gcm_a128kw.cose \
	./testfiles/es_dh_p384_a192gcm_a256kw.cose \
	./testfiles/es_dh_p384_a192gcm_a192kw.cose \
	./testfiles/es_dh_p384_a192gcm_a128kw.cose \
	./testfiles/es_dh_p384_a256gcm_a256kw.cose \
	./testfiles/es_dh_p384_a256gcm_a192kw.cose \
	./testfiles/es_dh_p384_a256gcm_a128kw.cose \
	./testfiles/es_dh_p521_a128gcm_a256kw.cose \
	./testfiles/es_dh_p521_a128gcm_a192kw.cose \
	./testfiles/es_dh_p521_a128gcm_a128kw.cose \
	./testfiles/es_dh_p521_a192gcm_a256kw.cose \
	./testfiles/es_dh_p521_a192gcm_a192kw.cose \
	./testfiles/es_dh_p521_a192gcm_a128kw.cose \
	./testfiles/es_dh_p521_a256gcm_a256kw.cose \
	./testfiles/es_dh_p521_a256gcm_a192kw.cose \
	./testfiles/es_dh_p521_a256gcm_a128kw.cose

.PHONY: test
test: $(TARGET) $(SOURCES)
	@for source in $(SOURCES); do\
		$(TARGET) $$source; \
	done

